### ISSUE TITLE
[RFC] Unset some config instead of forcing a config

### ISSUE THREAD

**Issue by yguedidi** [TomasVotruba/phpstan-bodyscan#23]
I see the config factory is forcing a fixed config, see https://github.com/TomasVotruba/phpstan-bodyscan/blob/main/src/PHPStanConfigFactory.php#L58-L63

Would be great to unset some settings when generating the config for phpstan-bodyscan like

- level
- ignored errors
- the baseline from includes

to preserve as much as possible from the project configuration, like:

- parallel config
- enabled extensions
- extensions config (Strict Rules, Symfony and Doctrine for example)
- custom rules
- conditional tags
- ...

What do you think?

**Comment by TomasVotruba** [comment]
The goal is to have comparable bare levels, no extensions, no ignores. To have a real gist of error count in the project.
That way it's comparable to other projects. We can also tract error count in time without interversion of "new added extension we forgot". Otherwise it would be just running your PHPStan setup multiple times :) no added value there.

This is at least the gist of a release post 
https://tomasvotruba.com/blog/get-quick-error-count-for-each-phpstan-level

**Comment by yguedidi** [comment]
@TomasVotruba so the use case of "help running PHPStan mulitple times on each level instead of doing it manually" is not in the scope of the project? I mean doing "just" that is not?
It could, in the context of a company project, help envision how to plan increasing PHPStan level over time

Would you accept to have it configurable? for example with command line flags like `--keep-extensions` or `--keep-rules`?

Side note: what about showing the number of errors per rule? as you have that other project that defines 300+ levels instead of PHPStan level :)

**Comment by TomasVotruba** [comment]
The goal here is to keep it simple to run and get the gist of project. Not to replace current PHPStan runner.
It's like hiring a developer and getting reading through their CV :)
